# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bmo6jfIqEiy2G-aLwqn-SxlnlXetJXDm
"""

pip install openai

#Import the Module
import openai

# Set up the OpenAI API client
api_key = "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"

# Function to classify sentences
def classify_chitchat(sentences):
    openai.api_key = api_key

    results = []

    for sentence in sentences:
        prompt = f"Classify the following sentence as chitchat or not:\n'{sentence}'\nOutput:"
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            temperature=0,
            max_tokens=50,  # Adjust the number of tokens as needed
            stop=None
        )
        output = response.choices[0].text.strip()  # Get the output text
        results.append((sentence, output))

    return results

# List of sentences to classify
sentences_to_classify = [
    "Just had a bad leak come from the AC",
    "Gotcha",
    "Hi",
    "Oh awesome",
    "Can anyone lift out cup table please?",
    "It went 13 times back to back had to use emergency stop to get it to stop"
]

# Classify sentences
classification_results = classify_chitchat(sentences_to_classify)

# Display results
for sentence, output in classification_results:
    print(f"Sentence: '{sentence}' -> Output: {output}")

